# Generated by Django 5.0.3 on 2024-04-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='transation_id',
            new_name='transaction_id',
        ),
    ]
