# Generated by Django 5.0.3 on 2024-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_transation_id_sale_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='activated',
        ),
        migrations.AddField(
            model_name='csv',
            name='csv_file',
            field=models.FileField(null=True, upload_to='csvs'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
